apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pubsub-ingress
  namespace: inspr-apps
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  rules:
    - host: inspr.com

      http:
        paths:
          - path: /publish
            backend:
              serviceName: pubsub-publish-front
              servicePort: 80