apiVersion: v1
kind: dapp

meta:
  name: "multibrokerexample"
spec:
  node:
    meta:
      name: multibrokerexample
    spec:
      image: gcr.io/insprlabs/examples/mbtest:latest
      replicas: 1

  boundary:
    channels:
      output:
        - mbch1
      input:
        - mbch1

