kind: dapp
apiVersion: v1

meta:
  name: discordpub
  parent: pubsub
spec:
  node:
    spec:
      replicas: 1
      image: gcr.io/insprlabs/inspr/examples/discordpub:latest
  boundary:
    channels:
      input:
        - pubsubch
