apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-deployment
  labels:
    app: reader

spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: reader
          image: gcr.io/insprlabs/inspr/example/kafkasa/reader:latest
          imagePullPolicy: Always
          ports:
            - name: reader-metrics
              containerPort: 16000
              protocol: TCP