# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.inspr.dev/inspr/core

stages:
  - build
  - test
  - deploy

build-cli:
  stage: build
  script:
    - bash build-cli.sh
  only:
    - develop
    - tags
  artifacts:
    paths:
      - bin/*
    expire_in: 30 days


unit-tests:
  stage: test
  script:
    - go test -v -coverprofile=profile.cov -coverpkg=./... ./...
    - go tool cover -func profile.cov
  coverage: '/^total:\s+\(statements\)\s+(\d+\.\d+)\%$/'

lint:
  stage: test
  script:
    - go get -u golang.org/x/lint/golint
    - golint --set_exit_status ./...


release-cli:
  stage: deploy
  script:
    bash .gitlab/scripts/release-cli.sh # get the built CLI, push it to gcloud or something, create a release on gitlab that contains the build CLIs
  only:
    - tags
