# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.inspr.dev/inspr/core
  VERSION: $(git describe --always)

stages:
  - build
  - test
  - release

build-cli:
  stage: build
  script:
    - bash .gitlab/scripts/buildcli.sh VERSION
  only:
    refs:
      - develop
      - tags
  artifacts:
    paths:
      - bin/
    expire_in: 30 days

push-cli:
  stage: build
  image: google/cloud-sdk
  script: 
    - bash .gitlab/scripts/pushcli.sh VERSION
  only:
    refs:
      - develop
      - tags
  dependencies:
    - build-cli

unit-tests:
  stage: test
  script:
    - go test -v -coverprofile=profile.cov -coverpkg=./... ./...
    - go tool cover -func profile.cov
  coverage: '/^total:\s+\(statements\)\s+(\d+\.\d+)\%$/'

lint:
  stage: test
  script:
    - go get -u golang.org/x/lint/golint
    - golint --set_exit_status ./...

release-cli:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - sh .gitlab/scripts/releasecli.sh VERSION
  only:
    - tags
  after_script:
    - echo "Release created!"
