coverage:
  status:
    project:
      default:
        target: auto
        # adjust accordingly based on how flaky your tests are
        # this allows a 10% drop from the previous base commit coverage
        threshold: 10%

ignore:
  - "examples/**/*" # ignore folders and all its contents
  - "**/*mock*" # wildcards accepted
  - "**/mock*/*"
  - "mock*.go"
  - "**/fake/*"
  - "**/main.go"
  - "**/interface*"
