apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: core
build:
  artifacts:
    - image: gcr.io/insprlabs/insprd
      context: .
      docker:
        dockerfile: cmd/insprd/Dockerfile
    - image: gcr.io/insprlabs/inspr/sidecar/lbsidecar
      context: .
      docker:
        dockerfile: cmd/sidecars/lbsidecar/Dockerfile
    - image: gcr.io/insprlabs/authsvc
      context: .
      docker:
        dockerfile: cmd/authsvc/Dockerfile
    - image: gcr.io/insprlabs/secretgen
      context: .
      docker:
        dockerfile: cmd/authsvc/secret/Dockerfile
deploy:
  helm:
    releases:
      - name: insprd
        artifactOverrides:
          insprdRepository: gcr.io/insprlabs/insprd
          lbsidecarImage: gcr.io/insprlabs/inspr/sidecar/lbsidecar
          authRepository: gcr.io/insprlabs/authsvc
          secretRepository: gcr.io/insprlabs/secretgen
        chartPath: build/helm
profiles:
  - name: uidp
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: gcr.io/insprlabs/uidp/redis/secret
          context: .
          docker:
            dockerfile: cmd/uid_provider/secret/Dockerfile
        - image: gcr.io/insprlabs/uidp/redis/api
          context: .
          docker:
            dockerfile: cmd/uid_provider/Dockerfile
    deploy:
      helm:
        releases:
          - name: uidp
            artifactOverrides:
              uidpRepository: gcr.io/insprlabs/uidp/redis/api
              secretRepository: gcr.io/insprlabs/uidp/redis/secret
            chartPath: build/uidp_helm
