apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: core
build:
  artifacts:
    - image: gcr.io/insprlabs/insprd
      context: .
      docker:
        dockerfile: ./build/Dockerfile
        buildArgs:
          TARGET: insprd

    - image: gcr.io/insprlabs/inspr/sidecar/lbsidecar
      context: .
      docker:
        dockerfile: ./build/Dockerfile
        buildArgs:
          TARGET: lbsidecar

    - image: gcr.io/insprlabs/authsvc
      context: .
      docker:
        dockerfile: ./build/Dockerfile
        buildArgs:
          TARGET: authsvc

    - image: gcr.io/insprlabs/secretgen
      context: .
      docker:
        dockerfile: ./build/Dockerfile
        buildArgs:
          TARGET: authsec

    - image: gcr.io/insprlabs/uidp/redis/secret
      context: .
      docker:
        dockerfile: ./build/Dockerfile
        buildArgs:
          TARGET: uidpsec

    - image: gcr.io/insprlabs/uidp/redis/api
      context: .
      docker:
        dockerfile: ./build/Dockerfile
        buildArgs:
          TARGET: uidp
deploy:
  helm:
    releases:
      - name: "{{ if .RELEASE_NAME }}{{ .RELEASE_NAME }}{{ else }}insprd{{ end }}"
        valuesFiles: 
          - "{{ .VALUES }}"
        artifactOverrides:
          image: gcr.io/insprlabs/insprd
          sidecar.image: gcr.io/insprlabs/inspr/sidecar/lbsidecar
          auth.image: gcr.io/insprlabs/authsvc
          secretGenerator.image: gcr.io/insprlabs/secretgen
        chartPath: build/insprd
        imageStrategy:
          helm:
            explicitRegistry: true
profiles:
  - name: uidp
    deploy:
      helm:
        releases:
          - name: "{{ if .RELEASE_NAME }}{{ .RELEASE_NAME }}{{ else }}uidp{{ end }}"
            valuesFiles: 
              - "{{ .VALUES }}"
            artifactOverrides:
              image: gcr.io/insprlabs/uidp/redis/api
              secret.image: gcr.io/insprlabs/uidp/redis/secret
            chartPath: build/uidp
            imageStrategy:
              helm:
                explicitRegistry: true
  - name: inspr-stack
    deploy:
      helm:
        releases:
          - name: "{{ if .RELEASE_NAME }}{{ .RELEASE_NAME }}{{ else }}inspr-stack{{ end }}"
            createNamespace: true
            valuesFiles: 
              - "{{ .VALUES }}"
            artifactOverrides:
              uidp.image: gcr.io/insprlabs/uidp/redis/api
              uidp.secret.image: gcr.io/insprlabs/uidp/redis/secret
              insprd.image: gcr.io/insprlabs/insprd
              insprd.sidecar.image: gcr.io/insprlabs/inspr/sidecar/lbsidecar
              insprd.auth.image: gcr.io/insprlabs/authsvc
              insprd.secretGenerator.image: gcr.io/insprlabs/secretgen
            chartPath: build/inspr-stack
            imageStrategy:
              helm:
                explicitRegistry: true

