apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: core
build:
  artifacts:
  - image: gcr.io/red-inspr/insprd
    context: .
    docker:
      dockerfile: cmd/insprd/Dockerfile
deploy:
  kubectl:
    manifests:
    - build/k8s/*.yaml
