apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: core
build:
  artifacts:
  - image: gcr.io/red-inspr/insprd
    context: .
    docker:
      dockerfile: cmd/insprd/Dockerfile
  - image: gcr.io/red-inspr/inspr/sidecar/kafka
    context: .
    docker:
      dockerfile: cmd/sidecars/kafka/Dockerfile
deploy:
  helm:
    releases:
    - name: insprd
      artifactOverrides:
        insprdRepository: gcr.io/red-inspr/insprd
        kafkaSidecarImage: gcr.io/red-inspr/inspr/sidecar/kafka
      chartPath: build/helm

profiles:
  - name: uidp
    build:
      artifacts:
      - image: gcr.io/red-inspr/uidp/redis/api
        context: .
        docker:
          dockerfile: cmd/uid_provider/Dockerfile
      - image: gcr.io/red-inspr/uidp/redis/secret
        context: .
        docker:
          dockerfile: cmd/uid_provider/secret/Dockerfile
    deploy:
      helm:
        releases:
        - name: uidp
          artifactOverrides:
            uidpApi: gcr.io/red-inspr/uidp/redis/api
            uidpSecret: gcr.io/red-inspr/uidp/redis/secret
          chartPath: build/uidp_helm