apiVersion: v1
kind: dapp

meta:
  name: receiver
  parent: atest.bench
spec:
  logLevel: debug
  node:
    spec:
      replicas: 1
      image: gcr.io/insprlabs/inspr/example/receiver:latest
  boundary:
    input:
      - receivech