apiVersion: v1
kind: dapp

meta:
  name: sender
  parent: bench
spec:
  logLevel: debug
  node:
    spec:
      replicas: 1
      image: gcr.io/insprlabs/inspr/example/sender:latest
  boundary:
    channels:
      output:
        - sendch
