apiVersion: v1
kind: dapp

meta:
  name: sender
  parent: atest.bench
spec:
  logLevel: debug
  node:
    spec:
      replicas: 1
      image: gcr.io/insprlabs/inspr/example/sender:latest
  boundary:
    output:
      - sendch
