kind: dapp
apiVersion: v1

meta:
  name: pubsubapi
  parent: pubsub
spec:
  node:
    spec:
      replicas: 1
      environment:
      image: gcr.io/red-inspr/inspr/example/pubsubapi:latest
  boundary:
    output:
      - pubsubch