kind: dapp
apiVersion: v1

meta:
  name: discordpub
  parent: pubsub
spec:
  node:
    spec:
      replicas: 1
      environment:
      image: gcr.io/insprlabs/inspr/example/discordpub:latest
  boundary:
    input:
      - pubsubch