apiVersion: v1
kind: dapp
meta:
  name: "filter"
  reference: ""
  parent: ""
spec:
  node:
    meta:
      name: "node-filter"
      parent: "filter"
    spec:
      image: gcr.io/red-inspr/inspr/examples/primes/filter:latest
      replicas: 1
      environment:
  
  boundary:
    input:
      - primes_ch1
    output:
      - primes_ch2
      