apiVersion: v1
kind: dapp
meta:
  name: "printer"
  reference: ""
  parent: ""
spec:
  node:
    meta:
      name: "node-printer"
      parent: "printer"
    spec:
      image: gcr.io/red-inspr/inspr/examples/primes/printer:latest
      replicas: 3
      environment:
        teste_env: "test"
  boundary:
    input:
      - primes_ch1
      - primes_ch2
    output:
      - primes_ch2
    
      
