apiVersion: v1
kind: dapp

meta:
  name: filter
  reference: ""
  parent: primesexample
spec:
  node:
    meta:
      name: node-filter
      parent: filter
    spec:
      image: gcr.io/red-inspr/inspr/examples/primes/filter:latest
      replicas: 3
  boundary:
    input:
      - filterinput
    output:
      - filteroutput
