apiVersion: v1
kind: dapp

meta:
  name: generator
  reference: ""
  parent: primesexample
spec:
  node:
    meta:
      name: node-generator
      parent: generator
    spec:
      image: gcr.io/insprlabs/inspr/examples/primes/generator:latest
      replicas: 3
      environment:
        MODULE: 100
  boundary:
    channels:
      output:
        - primesch1
