apiVersion: v1
kind: dapp

meta:
  name: router
spec:
  apps:
    client:
      meta:
        name: client
        parent: router
      spec:
        logLevel: debug
        node:
          spec:
            replicas: 1
            image: gcr.io/insprlabs/inspr/example/route/client:latest
    api:
      meta:
        name: api
        parent: router
      spec:
        logLevel: debug
        node:
          spec:
            replicas: 1
            image: gcr.io/insprlabs/inspr/example/route/api:latest
            endpoints:
              - add
              - sub
              - mul


