// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// OperatorClient is the client API for Operator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperatorClient interface {
	// Performs a node create operation
	CreateNode(ctx context.Context, in *NodeDescription, opts ...grpc.CallOption) (*NodeReply, error)
	// Performs a node de;ete operation
	DeleteNode(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*NodeReply, error)
	// Performs a node update operation
	UpdateNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*NodeReply, error)
	// Performs a node search / recover operation
	GetNode(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*NodeDescription, error)
	// Performs a node list operation
	ListNodes(ctx context.Context, in *Stub, opts ...grpc.CallOption) (*NodeDescriptionArray, error)
	// Returns the node status for each app
	UpdateNodeStatus(ctx context.Context, in *Stub, opts ...grpc.CallOption) (*NodeStatus, error)
}

type operatorClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorClient(cc grpc.ClientConnInterface) OperatorClient {
	return &operatorClient{cc}
}

func (c *operatorClient) CreateNode(ctx context.Context, in *NodeDescription, opts ...grpc.CallOption) (*NodeReply, error) {
	out := new(NodeReply)
	err := c.cc.Invoke(ctx, "/comunication.Operator/CreateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) DeleteNode(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*NodeReply, error) {
	out := new(NodeReply)
	err := c.cc.Invoke(ctx, "/comunication.Operator/DeleteNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) UpdateNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*NodeReply, error) {
	out := new(NodeReply)
	err := c.cc.Invoke(ctx, "/comunication.Operator/UpdateNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) GetNode(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*NodeDescription, error) {
	out := new(NodeDescription)
	err := c.cc.Invoke(ctx, "/comunication.Operator/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) ListNodes(ctx context.Context, in *Stub, opts ...grpc.CallOption) (*NodeDescriptionArray, error) {
	out := new(NodeDescriptionArray)
	err := c.cc.Invoke(ctx, "/comunication.Operator/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorClient) UpdateNodeStatus(ctx context.Context, in *Stub, opts ...grpc.CallOption) (*NodeStatus, error) {
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, "/comunication.Operator/UpdateNodeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorServer is the server API for Operator service.
// All implementations must embed UnimplementedOperatorServer
// for forward compatibility
type OperatorServer interface {
	// Performs a node create operation
	CreateNode(context.Context, *NodeDescription) (*NodeReply, error)
	// Performs a node de;ete operation
	DeleteNode(context.Context, *NodeID) (*NodeReply, error)
	// Performs a node update operation
	UpdateNode(context.Context, *Node) (*NodeReply, error)
	// Performs a node search / recover operation
	GetNode(context.Context, *NodeID) (*NodeDescription, error)
	// Performs a node list operation
	ListNodes(context.Context, *Stub) (*NodeDescriptionArray, error)
	// Returns the node status for each app
	UpdateNodeStatus(context.Context, *Stub) (*NodeStatus, error)
	mustEmbedUnimplementedOperatorServer()
}

// UnimplementedOperatorServer must be embedded to have forward compatible implementations.
type UnimplementedOperatorServer struct {
}

func (UnimplementedOperatorServer) CreateNode(context.Context, *NodeDescription) (*NodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedOperatorServer) DeleteNode(context.Context, *NodeID) (*NodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedOperatorServer) UpdateNode(context.Context, *Node) (*NodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedOperatorServer) GetNode(context.Context, *NodeID) (*NodeDescription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedOperatorServer) ListNodes(context.Context, *Stub) (*NodeDescriptionArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedOperatorServer) UpdateNodeStatus(context.Context, *Stub) (*NodeStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeStatus not implemented")
}
func (UnimplementedOperatorServer) mustEmbedUnimplementedOperatorServer() {}

// UnsafeOperatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorServer will
// result in compilation errors.
type UnsafeOperatorServer interface {
	mustEmbedUnimplementedOperatorServer()
}

func RegisterOperatorServer(s grpc.ServiceRegistrar, srv OperatorServer) {
	s.RegisterService(&_Operator_serviceDesc, srv)
}

func _Operator_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeDescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.Operator/CreateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).CreateNode(ctx, req.(*NodeDescription))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.Operator/DeleteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).DeleteNode(ctx, req.(*NodeID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.Operator/UpdateNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).UpdateNode(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.Operator/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).GetNode(ctx, req.(*NodeID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stub)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.Operator/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).ListNodes(ctx, req.(*Stub))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operator_UpdateNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stub)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServer).UpdateNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.Operator/UpdateNodeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServer).UpdateNodeStatus(ctx, req.(*Stub))
	}
	return interceptor(ctx, in, info, handler)
}

var _Operator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comunication.Operator",
	HandlerType: (*OperatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _Operator_CreateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _Operator_DeleteNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _Operator_UpdateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Operator_GetNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Operator_ListNodes_Handler,
		},
		{
			MethodName: "UpdateNodeStatus",
			Handler:    _Operator_UpdateNodeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/node.proto",
}
