apiVersion: v1
kind: dapp

meta:
  name: ping
  parent: pptable
spec:
  node:
    spec:
      replicas: 1
      image: gcr.io/red-inspr/inspr/example/ping:latest
  boundary:
    input:
      - pinginput
    output:
      - pingoutput
