kind: dapp
apiVersion: v1

meta:
  name: ping
  parent: pptable
spec:
  node:
    spec:
      replicas: 1
      environment:
        SUPER_SECRET_0001: "false"
      image: gcr.io/red-inspr/inspr/example/ping:latest
  boundary:
    input:
      - pinginput
    output:
      - pingoutput
