apiVersion: v1
kind: dapp

meta:
  name: ping
  parent: pptable
spec:
  logLevel: debug
  node:
    spec:
      replicas: 1
      image: gcr.io/insprlabs/inspr/example/ping:latest
      environment:
        SUPER_SECRET_0001: "false"
  boundary:
    channels:
      input:
        - pinginput
      output:
        - pingoutput
