apiVersion: v1
kind: dapp

meta:
  name: pong
  parent: pptable
spec:
  node:
    spec:
      image: gcr.io/insprlabs/inspr/example/pong:latest
  boundary:
    channels:
      input:
        - ponginput
      output:
        - pongoutput
