apiVersion: v1
kind: dapp

meta:
  name: pong
  parent: pptable
spec:
  node:
    spec:
      replicas: 1
      image: gcr.io/red-inspr/inspr/example/pong:latest
  boundary:
    input:
      - ponginput
    output:
      - pongoutput
