apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-deployment
  labels:
    app: writer

spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer

    spec:
      containers:
        - name: writer
          image: gcr.io/insprlabs/inspr/example/kafkasa/writer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80