apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-deployment
  labels:
    app: writer

spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: writer
          image: gcr.io/insprlabs/inspr/example/kafkasa/writer:latest
          imagePullPolicy: Always
          ports:
            - name: writer-metrics
              containerPort: 16000
              protocol: TCP