apiVersion: "v1"
kind: "dapp"
meta:
  name: "app1"
spec:
  boundary:
    input:
      - "bananita"
  types:
    ct1:
      schema: '{"type":"string"}'
  channels:
    ch1:
      spec:
        type: "ct1"
  apps:
    app4:
      spec:
        boundary:
          input:
          - "ch1"