apiVersion: v1
kind: dapp

meta:
  name: bench
spec:
  aliases:
    sender.sendch:
      target: benchannel
    receiver.receivech:
      target: benchannel
  boundary:
    input:
      - benchannel
    output:
      - benchannel
