apiVersion: v1
kind: dapp

meta:
  name: bench
spec:
  aliases:
    sender.sendch:
      resource: benchannel
    receiver.receivech:
      resource: benchannel
  boundary:
    channels:
      input:
        - benchannel
      output:
        - benchannel
  apps:
    sender:
      meta:
        name: sender
        parent: bench
      spec:
        logLevel: debug
        node:
          spec:
            replicas: 1
            image: gcr.io/insprlabs/inspr/example/sender:latest
        boundary:
          channels:
            output:
              - sendch
    receiver:
      meta:
        name: receiver
        parent: bench
      spec:
        logLevel: debug
        node:
          spec:
            replicas: 1
            image: gcr.io/insprlabs/inspr/example/receiver:latest
            endpoints:
              - edp1
              - edp2
        boundary:
          channels:
            input:
              - receivech


