kind: dapp
apiVersion: v1

meta:
  name: chtest
spec:
  node:
    spec:
      replicas: 1
      environment:
        SUPER_SECRET_0001: "false"
      image: gcr.io/insprlabs/inspr/example/chtest:latest
  boundary:
    channels:
      input:
        - checkch
      output:
        - testch1
        - testch2
        - testch3