apiVersion: v1
kind: dapp
meta:
  name: "basicexample"
spec:
  channeltypes:
    primes_ct1:
      meta:
        name: "primes_ct1"
      schema: '{"type":"int"}'
    primes_ct2:
      meta:
        name: "primes_ct2"
      schema: '{"type":"int"}'

  channels:
    primes_ch1:
      meta:
        name: "primes_ch1"
        reference: ""
        annotations:
          kafka.partition.number: "10"
          kafka.replication.factor: "3"
        parent: ""
      spec:
        type: "primes_ct1"
    primes_ch2:
      meta:
        name: "primes_ch2"
        reference: ""
        annotations:
          kafka.partition.number: "3"
          kafka.replication.factor: "3"
        parent: ""
      spec:
        type: "primes_ct2"

  aliases:
    primes.input:
      target: primes_ch1
    primes.output:
      target: primes_ch2

  apps:
    # number generators
    generator:
      spec:
        node:
          spec:
            image: gcr.io/red-inspr/inspr/examples/primes/generator:latest
            replicas: 8
            environment:
              MODULE: 300
        boundary:
          output:
            - primes_ch1

    primes:
      spec:
        boundary:
          input:
            - input
          output:
            - output
        aliases:
          printer.input:
            target: output
        apps:
          # filters primes
          filter:
            meta:
              name: "filter"
              reference: ""
              parent: ""
            spec:
              node:
                spec:
                  image: gcr.io/red-inspr/inspr/examples/primes/filter:latest
                  replicas: 2
              boundary:
                input:
                  - input
                output:
                  - output

          # prints the filtered
          printer:
            meta:
              name: "printer-primes"
              reference: ""
              parent: ""
            spec:
              node:
                meta:
                  name: "node-printer"
                  parent: "printer"
                spec:
                  image: gcr.io/red-inspr/inspr/examples/primes/printer:latest
                  replicas: 1
              boundary:
                input:
                  - input
