apiVersion: v1
kind: dapp
meta:
  name: "basic-example"
  reference: ""
  parent: ""
  Annotations: 
    kafka.partition.number: "1"
    kafka.replication.factor: "1"
spec:
  channeltypes:
    primes_ct1:
      meta:
        name: "primes_ct1"
      schema: '{"type":"int"}'
    primes_ct2:
      meta:
        name: "primes_ct2"
      schema: '{"type":"int"}'

  channels:
    primes_ch1:
      meta:
        name: "primes_ch1"
        reference: ""
        Annotations: 
          kafka.partition.number: "1"
          kafka.replication.factor: "1"
        parent: ""  
      spec:
        type: "primes_ct1"
    primes_ch2:
      meta:
        name: "primes_ch2"
        reference: ""
        Annotations:     
          kafka.partition.number: "1"
          kafka.replication.factor: "1"
        parent: ""  
      spec:
        type: "primes_ct2"
        
         
  apps:
    # number generators
    generator:
      meta:
        name: "generator"
      spec:
        node:
          meta:
            name: "node-generator"
            parent: "generator"
          spec:
            image: gcr.io/red-inspr/inspr/examples/primes/generator:latest
            replicas: 3
            environment:
              MODULE: 100
        boundary:
          input:
            - primes_ch2
          output:
            - primes_ch1

    # filters primes
    filter: 
      meta:
        name: "filter-primes"
        reference: ""
        parent: ""
      spec:
        node:
          meta:
            name: "node-filter"
            parent: "filter"
          spec:
            image: gcr.io/red-inspr/inspr/examples/primes/filter:latest
            replicas: 3            

        boundary:
          input:
            - primes_ch1
          output:
            - primes_ch2
        
        

    # prints the filtered
    printer: 
      meta:
        name: "printer-primes"
        reference: ""
        parent: ""
      spec:        
        node:
          meta:
            name: "node-printer"
            parent: "printer"
          spec:
            image: gcr.io/red-inspr/inspr/examples/primes/printer:latest
            replicas: 3            
        boundary:
          input:
            - primes_ch1
            - primes_ch2
          output:
            - primes_ch2
