apiVersion: v1
kind: dapp
meta:
  name: "basicexample"
spec:
  types:
    primes_ct1:
      meta:
        name: "primes_ct1"
      schema: '{"type":"int"}'
    primes_ct2:
      meta:
        name: "primes_ct2"
      schema: '{"type":"int"}'

  channels:
    primesch1:
      meta:
        name: "primesch1"
        reference: ""
        parent: ""
      spec:
        type: "primes_ct1"
        brokerlist:
          - kafka
    primesch2:
      meta:
        name: "primesch2"
        reference: ""
        parent: ""
      spec:
        type: "primes_ct2"
        brokerlist:
          - kafka

  aliases:
    primes.input:
      target: primesch1
    primes.output:
      target: primesch2

  apps:
    # number generators
    generator:
      meta:
        name: generator
      spec:
        node:
          spec:
            image: gcr.io/red-inspr/inspr/examples/primes/generator:latest
            replicas: 1
            environment:
              MODULE: 300
        boundary:
          output:
            - primesch1

    primes:
      meta:
        name: primes
      spec:
        boundary:
          input:
            - input
          output:
            - output
        aliases:
          printer.input:
            target: output
        apps:
          # filters primes
          filter:
            meta:
              name: "filter"
              reference: ""
              parent: ""
            spec:
              node:
                spec:
                  image: gcr.io/red-inspr/inspr/examples/primes/filter:latest
                  replicas: 2
              boundary:
                input:
                  - input
                output:
                  - output

          # prints the filtered
          printer:
            meta:
              name: "printer"
              reference: ""
              parent: ""
            spec:
              node:
                meta:
                  name: "printer"
                spec:
                  image: gcr.io/red-inspr/inspr/examples/primes/printer:latest
                  replicas: 1
              boundary:
                input:
                  - output
