apiVersion: v1
kind: dapp

meta:
  name: primesexample
spec:
  types:
    primes_ct1:
      meta:
        name: "primes_ct1"
      schema: '{"type":"int"}'
    primes_ct2:
      meta:
        name: "primes_ct2"
      schema: '{"type":"int"}'

  channels:
    primesch1:
      meta:
        name: "primesch1"
        reference: ""
        parent: ""
      spec:
        type: "primes_ct1"
        brokerlist:
          - kafka
    primesch2:
      meta:
        name: "primesch2"
        reference: ""
        parent: ""
      spec:
        type: "primes_ct2"
        brokerlist:
          - kafka

  apps:
    # number generators
    generator:
      meta:
        name: generator
      spec:
        node:
          spec:
            image: gcr.io/insprlabs/inspr/examples/primes/generator:latest
            replicas: 1
            environment:
              MODULE: 300
        boundary:
          channels:
            output:
              - primesch1

    primes:
      meta:
        name: primes
      spec:
        aliases:
          filterinput:
            destination: filter
            resource: primesch1
          filteroutput:
            destination: filter
            resource: primesch2
          printerinput:
            destination: printer
            resource: primesch2

        apps:
          # filters primes
          filter:
            meta:
              name: filter
              reference: ""
              parent: "primes"
            spec:
              node:
                spec:
                  image: gcr.io/insprlabs/inspr/examples/primes/filter:latest
                  replicas: 2
              boundary:
                channels:
                  input:
                    - filterinput
                  output:
                    - filteroutput

          # prints the filtered
          printer:
            meta:
              name: "printer"
              reference: ""
              parent: "primes"
            spec:
              node:
                meta:
                  name: "printer"
                spec:
                  image: gcr.io/insprlabs/inspr/examples/primes/printer:latest
                  replicas: 1
              boundary:
                channels:
                  input:
                    - printerinput
