apiVersion: v1
kind: dapp
meta:
  name: "basic-example"
spec:
  channeltypes:
    ct1:
      schema: '{"type":"string"}'

  channels:
    ch1:
      spec:
        type: "ct1"
    ch2:
      spec:
        type: "ct1"
         
  apps:
    # number generators
    generator:
      meta:
        name: "generator"
      spec:
        node:
          meta:
            name: "node-number-generator"
            parent: "number-generator"
          spec:
            image: gcr.io/red-inspr/generator
            replicas: 3
            environment:
              MODULE: 100

    # filters primes
    filter: 
      meta:
        name: "filter-primes"
      spec:
        node:                
          image: gcr.io/red-inspr/primes-filter
          replicas: 3 

        boundary:
          input:
            - "ch1"
          output:
            - "ch2"
        
        node:
          meta:
            name: "node-number-generator"
            parent: "number-generator"
          spec:
            image: gcr.io/red-inspr/generator
            replicas: 3
            environment:
              teste_env: "test"

    # prints the filtered
    print: 
      meta:
        name: "printer-primes"
      spec:
        node:
          image: gcr.io/red-inspr/primes-printer
        boundary:
          input:
            - "ch2"                
