{
 "title": "Inspr query board",
 "description": "Inspr dashboards and panels",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "sender_name", "query": "bench-sender" },
   { "name": "receiver_name", "query": "bench-receiver" }
  ]
 },
 "panels": [
  {
   "title": "Message Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message write delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(inspr_sidecar_send_message_duration_sum{inspr_app=\"${sender_name}\"}[1m]) \n/ \nrate(inspr_sidecar_send_message_duration_count{inspr_app=\"${sender_name}\"}[1m])",
       "legendFormat": "kafka_sidecar"
      },
      {
       "expr": "rate(inspr_lbsidecar_send_message_duration_sum{inspr_app=\"${sender_name}\"}[1m]) \n/ \nrate(inspr_lbsidecar_send_message_duration_count{inspr_app=\"${sender_name}\"}[1m])",
       "legendFormat": "lbsidecar"
      }
     ]
    },
    {
     "title": "Message read delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "rate(inspr_sidecar_read_message_duration_sum{inspr_app=\"${receiver_name}\"}[1m]) \n/ \nrate(inspr_sidecar_read_message_duration_count{inspr_app=\"${receiver_name}\"}[1m])",
       "legendFormat": "kafka_sidecar"
      },
      {
       "expr": "rate(inspr_lbsidecar_read_message_duration_sum{inspr_app=\"${receiver_name}\"}[1m]) \n/ \nrate(inspr_lbsidecar_read_message_duration_count{inspr_app=\"${receiver_name}\"}[1m])",
       "legendFormat": "lbsidecar"
      }
     ]
    },
    {
     "title": "message rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(inspr_lbsidecar_message_send{}[5m]) ",
       "legendFormat": "send_message"
      },
      {
       "expr": "rate(inspr_lbsidecar_message_read{}[5m])",
       "legendFormat": "read_message"
      }
     ]
    },
    {
     "title": "Throughput (Reads x Writes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "increase(inspr_lbsidecar_message_read{inspr_app=\"${receiver_name}\"}[1m])",
       "legendFormat": "lb_receiver"
      },
      {
       "expr": "increase(inspr_lbsidecar_message_send{inspr_app=\"${sender_name}\"}[1m])",
       "legendFormat": "lb_sender"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Writer Steps Durations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(inspr_kafka_sidecar_writer_flush_duration_sum{inspr_app=\"${sender_name}\"}[1m]) \n/\nrate(inspr_kafka_sidecar_writer_flush_duration_count{inspr_app=\"${sender_name}\"}[1m])",
       "legendFormat": "Flush Dur"
      },
      {
       "expr": "rate(inspr_kafka_sidecar_writer_produce_message_duration_sum{inspr_app=\"${sender_name}\"}[1m]) \n/ \nrate(inspr_kafka_sidecar_writer_produce_message_duration_count{inspr_app=\"${sender_name}\"}[1m])",
       "legendFormat": "Produce Message Dur"
      },
      {
       "expr": "rate(inspr_kafka_sidecar_writer_resolve_channel_duration_sum{inspr_app=\"${sender_name}\"}[1m]) \n/ \nrate(inspr_kafka_sidecar_writer_resolve_channel_duration_count{inspr_app=\"${sender_name}\"}[1m])",
       "legendFormat": "Resolve Channel Dur"
      }
     ]
    },
    {
     "title": "Kafka Reader  Steps Durations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "inspr_kafka_read_kafka_time_duration_sum{app_name=\"receiver\"}\n/\ninspr_kafka_read_kafka_time_duration_count{app_name=\"receiver\"}",
       "legendFormat": "Reader kafka duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "send and receive error rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(inspr_lbsidecar_message_send_error{}[5m])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(inspr_lbsidecar_message_send_error{}[5m])",
       "legendFormat": "send"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "go_threads_and_routines",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "targets": [
      { "expr": "go_threads{}", "legendFormat": "threads" },
      { "expr": "go_goroutines{}", "legendFormat": "routines" }
     ]
    },
    {
     "title": "gc_duration_seconds_sum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "targets": [
      { "expr": "go_gc_duration_seconds_sum{}" }
     ]
    },
    {
     "title": "gc_by_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{app_id=~\"bench-receiver|bench-sender\"}"
      }
     ]
    },
    {
     "title": "mem_alloc_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      { "expr": "go_memstats_alloc_bytes{}", "legendFormat": "allocation" }
     ]
    }
   ]
  }
 ]
}