name: Test and coverage

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"
      # - name: Download golint
      #   run: go get -u golang.org/x/lint/golint
      # - name: Lint packages
      #   run: golint -set_exit_status ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: -D errcheck -D deadcode -D varcheck

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go.
          # skip-go-installation: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"
      - name: Run coverage
        run: go test -coverprofile=profile.cov.tmp -coverpkg=./... ./... || exit 1
      - name: Filter files
        run: cat profile.cov.tmp | grep -v 'fake\|mock\|doc\|examples\|main\|interface' > coverage.out
      # - name: Upload coverage to Codecov
      #   run: bash <(curl -s https://codecov.io/bash) -f
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./profile.cov.tmp
          flags: unittests
          name: codecov-umbrella
