name: Test and coverage

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.29


  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"
      - name: Run coverage
        run: go test -coverprofile=profile.cov.tmp -coverpkg=./... ./... || exit 1 
      - name: Filter files
        run: cat profile.cov.tmp | grep -v 'fake\|mock\|doc\|examples\|main.go' > coverage.out
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -f 
  
  
