name: "tagged-release"

on:
  push
  # branches:
  #   - develop
  # tags:
  #   - "v*"

env:
  GCR_FILENAME: "${{ github.sha }}"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: |
            kubectl
            helmv3
            skaffold
          kubectl: "1.20.2"
          helmv3: "3.5.4"
          skaffold: "1.21.0"
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@master
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      #     export_default_credentials: true
      - name: Create file with GCR stuff
        run: 'echo "$GCR_KEY" > $GCR_FILENAME.json'
        shell: bash
        env:
          GCR_KEY: ${{ secrets.GCR_ACCOUNT_KEY }}

      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: "red-inspr"
          APPLICATION_CREDENTIALS: ${{ secrets.GCR_ACCOUNT_KEY }}
        with:
          args: auth activate-service-account ${{ secrets.GCR_ACCOUNT }}--key-file=$GCR_FILENAME.json

      # - name: Build CLI
      #   run: bash .github/scripts/buildcli.sh

      - name: Create temp file to store skaffold build return
        run: |
          touch tags.out

      - name: Run skaffold build
        run: |
          skaffold build --file-output=tags.out --filename=/home/runner/work/inspr/inspr/skaffold.yaml

      # - name: Run Skaffold build
      #   uses: hiberbee/github-action-skaffold@latest
      #   with:
      #     cache-artifacts: false
      #     command: build --file-output=tags.out --filename=/home/runner/work/inspr/inspr/skaffold.yaml

      - name: Helm Chart update
        run: bash .github/scripts/update_tags.sh https://inspr-charts.storage.googleapis.com/ gs://inspr-charts

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Release ${{ github.sha }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.jar
            bin/*
