name: "Tagged Release"

on:
  push:
    tags:
      - "v*"

env:
  GCR_FILENAME: "${{ github.sha }}"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: |
            kubectl
            helmv3
            skaffold
          kubectl: "1.20.2"
          helmv3: "3.5.4"
          skaffold: "1.21.0"
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: insprlabs
          export_default_credentials: true

      - name: Create file with GCR stuff
        run: 'echo "$GCR_KEY" > /tmp/$GCR_FILENAME.json'
        shell: bash
        env:
          GCR_KEY: ${{ secrets.GCR_ACCOUNT_KEY }}

      - name: Configure GCR service account
        run: |
          gcloud auth activate-service-account ${{ secrets.GCR_ACCOUNT }} --key-file=/tmp/$GCR_FILENAME.json

      - name: Run skaffold build
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/$GCR_FILENAME.json
        run: |
          skaffold build --profile=inspr-stack --filename=/home/runner/work/inspr/inspr/skaffold.yaml

      - name: Publish helm charts
        run: "cd scripts && bash update-charts.sh"

      - name: Build CLI
        run: bash .github/scripts/buildcli.sh

      - name: Push CLI
        run: bash .github/scripts/pushcli.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Release ${{ github.sha }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.jar
            bin/*
