apiVersion: v1
kind: dapp
meta:
  name: "number-generator"
  reference: ""
  parent: ""
spec:
  node:
    meta:
      name: "node-number-generator"
      parent: "number-generator"
    spec:
      image: ...
      replicas: 3
      environment:
        teste_env: "test"
  
  boundary:
    output:
      - ch1