apiVersion: v1
kind: dapp
meta:
  name: "number-generator"
  reference: ""
  parent: ""
spec:
  node:
    meta:
      name: "node-number-generator"
      parent: "number-generator"
    spec:
      image: gcr.io/red-inspr/generator
      replicas: 3
      environment:
        MODULE: 100
  
  boundary:
    output:
      - ch1
      