apiVersion: v1
kind: dapp
meta:
  name: "num-printer"
spec:
  channels:
    ch1:
      meta:
        name: "printer-ch"
        reference: ""
        parent: ""
      spec:
        type: "ct1"

  node:
    meta:
      name: "node-primes"
      parent: ""
    spec:
      image: ...
      replicas: 3
      environment:
        teste_env: "test"
  
  boundary:
    input:
      - ch1    