apiVersion: v1
kind: dapp
meta:
    name: "controllerexample"
spec:
    auth:
        scope: ""
        permissions: ["create:dapp", "delete:dapp", "update:dapp"]
    node:
        spec:
            ports:
                - port: 8080
                  targetPort: 8000
            image: gcr.io/insprlabs/inspr/example/controller:latest
            replicas: 1
