apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: controller-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: inspr.com
      http:
        paths:
          - path: /update
            pathType: Prefix
            backend:
              service:
                name: node-de64309b-0b62-43db-98b3-0f519c6a2711
                port:
                  number: 8080
          - path: /delete
            pathType: Prefix
            backend:
              service:
                name: node-de64309b-0b62-43db-98b3-0f519c6a2711
                port:
                  number: 8080
          - path: /create
            pathType: Prefix
            backend:
              service:
                name: node-de64309b-0b62-43db-98b3-0f519c6a2711
                port:
                  number: 8080
