
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: controller-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: inspr.com
    http:
      paths:
      - path: /update
        backend:
            serviceName: node-9cfecea5-2f9e-49f0-ada9-d2ccc93702f2
            servicePort: 8080
      - path: /delete
        backend:
            serviceName: node-9cfecea5-2f9e-49f0-ada9-d2ccc93702f2
            servicePort: 8080
      - path: /create
        backend:
            serviceName: node-9cfecea5-2f9e-49f0-ada9-d2ccc93702f2
            servicePort: 8080
